apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: riffraff-data-claim
spec:
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  selector:
    matchLabels:
      name: riffraff-data-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: riffraff-data-pv
  labels:
    name: riffraff-data-pv
spec:
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce #type of access
  capacity:
    storage: 10Mi #Size of the volume
  hostPath:
    path: "/storage/volumes/riffraff"
